### ISSUE TITLE
Incorporate Common Modeling Best Practices

### ISSUE THREAD

**Issue by eogilvy12** [fishtown-analytics/cloud_sandbox#4]
Incorporate the below common modeling patterns to establish best practices:

Complete:
* Joining tables (in `fct_orders` and `dim_customers`)
* Aggregating to the same grain and joining (in `fct_orders` and `dim_customers`)

Incomplete:
* Coalescing with full outer join
* Date spinning
* Sum(case when …) statements to pivot tables
* Metrics table
* Sessionizing
* Unioning together data
    * Unioning together when tables have duplicate ids
* Inner join to exclude filtered relational data (like orders into items)
* Amortizing revenue (MRR)
* Group by macro
* Using a macro when two models have the same logic (convert timestamp?)
* Attribution

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
